//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveUncertainty.classes.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table4
    {
        public int Id { get; set; }
        public string a { get; set; }
        public string b { get; set; }
        public string c { get; set; }
        public string k { get; set; }
        public string u { get; set; }
        public string g { get; set; }
        public string q { get; set; }
        public string f { get; set; }
        public string s { get; set; }
        public string w { get; set; }
        public string Gasid { get; set; }
    }
}
