//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveUncertainty.classes.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table5
    {
        public int Id { get; set; }
        public string Gasid { get; set; }
        public string Mr { get; set; }
        public string Ea { get; set; }
        public string Ka { get; set; }
        public string Qa { get; set; }
        public string S { get; set; }
        public string Ga { get; set; }
        public string Fa { get; set; }
        public string W { get; set; }
    }
}
